---

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - slack
    - vlc
#    - google-drive
#    - keepingyouawake
- name: install brew applications for all users
  homebrew: name={{item}} state=latest
  with_items:
    - dos2unix
    - ffmpeg
    - mpv
    - vim
    - graphviz
