---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install sysadmin brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - mtr
    - rsync
    - watch
    - htop
    - tree
    - wget
    - iperf
    - ssh-copy-id
    - netcat
    - ipmitool
    - awscli

- name: install sysadmin cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
#    - phpstorm
#    - sequel-pro
    - java
